### ISSUE TITLE
Fatal error when activating plugin on PHP 7

### ISSUE THREAD

**Issue by eliotharper** [bigbitecreative/wordpress-git-content#2]
I've tried activating the plugin in PHP version 7.0.30 and 7.2.5 but get a fatal error when activating the plugin.

Version 7.2.5 returns the fatal error "Cannot use vierbergenlars\Lib Js\Object"

**Comment by eliotharper** [comment]
Note that in the latest WordPress version (4.9.6) you can't even activate the plug-in in WordPress as you get the error:

> Fatal error: Uncaught Error: Call to undefined function Illuminate\Support\mb_strpos() in /app/wp-content/plugins/wordpress-git-content-master/vendor/illuminate/support/Str.php:72 Stack trace: #0 /app/wp-content/plugins/wordpress-git-content-master/vendor/illuminate/http/Request.php(696): Illuminate\Support\Str::contains(NULL, Array) #1 /app/wp-content/plugins/wordpress-git-content-master/vendor/illuminate/http/Request.php(664): Illuminate\Http\Request->isJson() #2 /app/wp-content/plugins/wordpress-git-content-master/vendor/illuminate/http/Request.php(847): Illuminate\Http\Request->getInputSource() #3 /app/wp-content/plugins/wordpress-git-content-master/vendor/illuminate/http/Request.php(57): Illuminate\Http\Request::createFromBase(Object(Herbert\Framework\Http)) #4 /app/wp-content/plugins/wordpress-git-content-master/vendor/getherbert/framework/Herbert/Framework/Providers/HerbertServiceProvider.php(31): Illuminate\Http\Request::capture() #5 /app/wp-content/plugins/wordpress-git-content-master/vendor/getherbert/framework/ in /app/wp-content/plugins/wordpress-git-content-master/vendor/illuminate/support/Str.php on line 72
